<%--
Designer: Michael Cheeseman
Page Name: About.aspx
Last Edit: March 28, 2014
--%>

<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="About.aspx.cs" Inherits="Cheeseman.About" %>

<asp:Content ID="Content1" ContentPlaceHolderID="Heading" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="Main" runat="server">
    <h2>
        About
    </h2>
    <p>
        This is my final web project. Across this website are tools learned throughout the course all put together. Click on the tabs above to access each week
        and to see the content. All code written is either created by me, from the lectures from the class, or auto-generated by Microsoft Visual studio. 
    </p>
</asp:Content>
